"""Parser and finder for structured AGENTS.md rule sections.

Format supported in the ## [rules] section:
    param:     <glob>  -> must_have: <param_name>
    decorator: <glob>  -> must_have: <decorator_name>
    forbidden: <glob>  -> no: <literal_pattern>

Lines starting with # are comments. Other sections (## Stack, ## [thresholds], etc.)
are preserved as-is and not parsed here.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from fnmatch import fnmatch
from pathlib import Path
from typing import List, Optional

_MAX_SEARCH_DEPTH = 8
_RULE_RE = re.compile(
    r"^(param|decorator|forbidden)\s*:\s*(.+?)\s*->\s*(must_have|no)\s*:\s*(.+)$"
)


@dataclass(frozen=True)
class AgentRule:
    rule_type: str      # "param" | "decorator" | "forbidden"
    glob: str           # e.g. "apps/services/**"
    constraint: str     # e.g. "must_have:usuario" or "no:fields='__all__'"
    raw: str            # original line for error messages

    @property
    def constraint_type(self) -> str:
        return self.constraint.split(":", 1)[0]

    @property
    def constraint_value(self) -> str:
        return self.constraint.split(":", 1)[1]


def find_agents_md(start: Path) -> Optional[Path]:
    """Walk up from *start* directory looking for AGENTS.md."""
    cur = start if start.is_dir() else start.parent
    for _ in range(_MAX_SEARCH_DEPTH):
        candidate = cur / "AGENTS.md"
        if candidate.exists():
            return candidate
        if cur.parent == cur:
            break
        cur = cur.parent
    return None


def parse_rules(agents_md: Path) -> List[AgentRule]:
    """Extract and parse the ## [rules] section from AGENTS.md."""
    try:
        content = agents_md.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return []

    in_rules = False
    rules: List[AgentRule] = []

    for line in content.splitlines():
        stripped = line.strip()
        if stripped == "## [rules]":
            in_rules = True
            continue
        if in_rules and stripped.startswith("## "):
            break
        if not in_rules or not stripped or stripped.startswith("#"):
            continue
        m = _RULE_RE.match(stripped)
        if m:
            rule_type, glob, ctype, value = m.groups()
            rules.append(AgentRule(
                rule_type=rule_type,
                glob=glob.strip(),
                constraint=f"{ctype}:{value.strip()}",
                raw=stripped,
            ))

    return rules


def rules_for_file(filepath: Path, rules: List[AgentRule]) -> List[AgentRule]:
    """Return rules whose glob matches *filepath* (relative to its project root)."""
    matched: List[AgentRule] = []
    for rule in rules:
        # Try matching against the full path string and each suffix
        fp_str = filepath.as_posix()
        glob = rule.glob.replace("\\", "/")
        if fnmatch(fp_str, glob) or fnmatch(filepath.name, glob):
            matched.append(rule)
            continue
        # Also try matching against trailing parts of the path
        parts = filepath.parts
        for i in range(len(parts)):
            partial = "/".join(parts[i:])
            if fnmatch(partial, glob):
                matched.append(rule)
                break
    return matched


# ---------------------------------------------------------------------------
# Templates generated by `code-analyze init`
# ---------------------------------------------------------------------------

_DJANGO_TEMPLATE = """\
# AGENTS.md
<!-- Gerado por code-analyze init {version} | Editavel -->

## Stack
Django | Python | PostgreSQL

## Arquitetura
<!-- Descreva os modulos principais -->
<!-- Exemplo:
apps/brain/      -- logica de negocio
apps/services/   -- camada de servicos (I/O externo aqui)
apps/api/        -- endpoints REST apenas
-->

## [rules]
# Regras validadas por: code-analyze check <arquivo.py>
# Sintaxe: tipo: glob -> constraint: valor
#
# param:     garante que funcoes no glob tenham o parametro
# decorator: garante que funcoes no glob tenham o decorador
# forbidden: garante que o padrao literal NAO apareca no arquivo

decorator: **/views.py        -> must_have: @login_required
forbidden: **                 -> no: fields='__all__'
forbidden: **                 -> no: cursor.execute(f"

## [thresholds]
min_score: 7.0
max_complexity: 10
max_class_lines: 200

## Debitos Conhecidos
<!-- Liste debitos tecnicos para contexto dos agentes de IA -->
"""

_FASTAPI_TEMPLATE = """\
# AGENTS.md
<!-- Gerado por code-analyze init {version} | Editavel -->

## Stack
FastAPI | Python | PostgreSQL

## Arquitetura
<!-- Descreva os modulos principais -->

## [rules]
# Regras validadas por: code-analyze check <arquivo.py>
forbidden: **       -> no: password
forbidden: **       -> no: cursor.execute(f"

## [thresholds]
min_score: 7.0
max_complexity: 10
max_class_lines: 200

## Debitos Conhecidos
<!-- Liste debitos tecnicos para contexto dos agentes de IA -->
"""

_GENERIC_TEMPLATE = """\
# AGENTS.md
<!-- Gerado por code-analyze init {version} | Editavel -->

## Stack
<!-- Descreva a stack do projeto -->

## Arquitetura
<!-- Descreva os modulos principais -->

## [rules]
# Regras validadas por: code-analyze check <arquivo.py>
# Exemplos:
# param:     apps/services/**  -> must_have: usuario
# decorator: apps/views/**     -> must_have: @login_required
# forbidden: **                -> no: fields='__all__'

## [thresholds]
min_score: 7.0
max_complexity: 10
max_class_lines: 200

## Debitos Conhecidos
<!-- Liste debitos tecnicos para contexto dos agentes de IA -->
"""

TEMPLATES = {
    "django": _DJANGO_TEMPLATE,
    "fastapi": _FASTAPI_TEMPLATE,
    "flask": _GENERIC_TEMPLATE,
    "generic": _GENERIC_TEMPLATE,
}


def generate_agents_md(project_type: str, version: str) -> str:
    template = TEMPLATES.get(project_type, _GENERIC_TEMPLATE)
    return template.replace("{version}", version)
