"""Centralised output limits used across detectors, reports, and the CLI."""
from __future__ import annotations

MAX_FINDINGS_PER_DETECTOR = 10
MAX_TOOL_FINDINGS = 20
MAX_DIFF_LINES_TERMINAL = 20
MAX_INTERACTIVE_PREVIEW_ITEMS = 3
MAX_REPORT_TOP_ITEMS = 5
MAX_TOP_RECOMMENDATIONS = 3
MAX_MISSING_TESTS_SAMPLE = 3
MAX_MISSING_TESTS_LIST = 10
MAX_CYCLES_LISTED = 10
